#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
empacotar_dossier_forense_zip.py - Cria o arquivo ZIP consolidado com todas as folhas, pecas, PDFs e relatorios organizados por ordem e pasta tematica.
"""

import os
import sys
import zipfile
from pathlib import Path

DEV_ROOT = Path(r"C:\Users\Yokozuna\Dev")
OUTPUT_DIR = DEV_ROOT / "OUTPUT_CENTRALIZADO"
PDF_DIR = OUTPUT_DIR / "05_PDFS_GERADOS_PARA_IMPRESSAO"
REPORTS_DIR = OUTPUT_DIR / "01_INDEX_E_RELATORIOS"
DOCS_DIR = OUTPUT_DIR / "04_DOCUMENTOS_CITIUS_E_PECAS"

ZIP_DEST = OUTPUT_DIR / "DOSSIER_FORENSE_COMPLETO_DEV_YOKOZUNA.zip"

PACKAGE_MAP = [
    # 01 - Compendios e Indices
    (PDF_DIR / "00_COMPENDIO_OFICIAL_ATOS_CITIUS_TODOS_PROCESSOS.pdf", "01_COMPENDIOS_E_INDICES_CITIUS/00_COMPENDIO_OFICIAL_ATOS_CITIUS_TODOS_PROCESSOS.pdf"),
    (REPORTS_DIR / "COMPENDIO_OFICIAL_ATOS_PROCESSUAIS_CITIUS.md", "01_COMPENDIOS_E_INDICES_CITIUS/COMPENDIO_OFICIAL_ATOS_PROCESSUAIS_CITIUS.md"),
    (REPORTS_DIR / "INDICE_MESTRE_CONSOLIDADO.md", "01_COMPENDIOS_E_INDICES_CITIUS/INDICE_MESTRE_CONSOLIDADO.md"),

    # 02 - Processo 23142 (Centenario / TRL)
    (PDF_DIR / "01_DESPACHO_INDEFERIMENTO_LIMINAR_PROC_23142.pdf", "02_PROCESSO_23142_EXECUCAO_CENTENARIO_TRL/01_DESPACHO_INDEFERIMENTO_LIMINAR_PROC_23142.pdf"),
    (PDF_DIR / "02_ACORDAO_TRL_EXTINCAO_EXECUCAO_23142.pdf", "02_PROCESSO_23142_EXECUCAO_CENTENARIO_TRL/02_ACORDAO_TRL_EXTINCAO_EXECUCAO_23142.pdf"),
    (PDF_DIR / "04_REQUERIMENTO_LEVANTAMENTO_PENHORAS_35K.pdf", "02_PROCESSO_23142_EXECUCAO_CENTENARIO_TRL/04_REQUERIMENTO_LEVANTAMENTO_PENHORAS_35K.pdf"),
    (REPORTS_DIR / "RECLAMACAO_CAAJ_E_QUADRO_FINANCEIRO_PROVAS.md", "02_PROCESSO_23142_EXECUCAO_CENTENARIO_TRL/RECLAMACAO_CAAJ_E_QUADRO_FINANCEIRO_PROVAS.md"),

    # 03 - Processo 3719 (Cautelar Arquivado / TRL)
    (REPORTS_DIR / "PROVA_IMPEDIMENTO_PRESENCA_SALA_AUDIENCIA_3719.md", "03_PROCESSO_3719_CAUTELAR_ARQUIVADO_TRL/PROVA_IMPEDIMENTO_PRESENCA_SALA_AUDIENCIA_3719.md"),
    (DOCS_DIR / "PROVA_CONFISSAO_WHATSAPP_FILIPE_DELGADO_20220823.md", "03_PROCESSO_3719_CAUTELAR_ARQUIVADO_TRL/PROVA_CONFISSAO_WHATSAPP_FILIPE_DELGADO_20220823.md"),

    # 04 - Processo 10153 e 20203 (UNICRE Suspenso)
    (PDF_DIR / "05_DESPACHO_SUSPENSAO_EXECUCAO_UNICRE_PROC_10153.pdf", "04_PROCESSO_10153_E_20203_UNICRE_SUSPENSO/05_DESPACHO_SUSPENSAO_EXECUCAO_UNICRE_PROC_10153.pdf"),
    (REPORTS_DIR / "PROVA_OMISSAO_DOLOSA_CITACOES_E_FRAUDE_MORADAS.md", "04_PROCESSO_10153_E_20203_UNICRE_SUSPENSO/PROVA_OMISSAO_DOLOSA_CITACOES_E_FRAUDE_MORADAS.md"),

    # 05 - Reclamacao CAAJ
    (PDF_DIR / "03_RECLAMACAO_DISCIPLINAR_CAAJ_LUISA_SANTOS.pdf", "05_RECLAMACAO_DISCIPLINAR_CAAJ_LUISA_SANTOS/03_RECLAMACAO_DISCIPLINAR_CAAJ_LUISA_SANTOS.pdf"),

    # 06 - Relatorios NLP e Auditoria
    (REPORTS_DIR / "RELATORIO_NLP_NER_SCIKIT.json", "06_RELATORIOS_NLP_E_AUDITORIA/RELATORIO_NLP_NER_SCIKIT.json")
]

def criar_zip_dossier():
    print("=" * 80)
    print(" A CRIAR PACOTE ZIP DO DOSSIER FORENSE ORGANIZADO")
    print(f" Destino: {ZIP_DEST}")
    print("=" * 80)

    count = 0
    with zipfile.ZipFile(ZIP_DEST, "w", zipfile.ZIP_DEFLATED) as zipf:
        for src, arcname in PACKAGE_MAP:
            if src.exists():
                zipf.write(src, arcname)
                print(f"[+] Adicionado: {arcname} ({src.stat().st_size} bytes)")
                count += 1
            else:
                print(f"[-] Nao encontrado: {src}")

    print("=" * 80)
    print(f" SUCESSO: {count} ficheiros empacotados com sucesso em:")
    print(f" {ZIP_DEST}")
    print(f" Tamanho Total do ZIP: {ZIP_DEST.stat().st_size / 1024:.1f} KB")
    print("=" * 80)

if __name__ == "__main__":
    criar_zip_dossier()
